In [24]:
import pandas as pd  
data=pd.read_csv('C:\\Users\\zbook\\Desktop\\Smart study planner project\\student_study_habits.csv')
data

,study_hours_per_week,sleep_hours_per_day,attendance_percentage,assignments_completed,final_grade,participation_level_Low,participation_level_Medium,internet_access_Yes,parental_education_High School,parental_education_Master's,parental_education_PhD,extracurricular_Yes,part_time_job_Yes
0,346,409,449,2,431,0,1,1,0,0.0,0,1,0
1,219,487,392,5,216,0,1,1,0,0.0,0,0,0
2,376,36,241,9,285,0,1,1,0,0.0,0,1,0
3,465,351,115,2,320,1,0,1,0,0.0,0,1,0
4,201,115,365,3,133,0,1,1,1,0.0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,357,190,450,2,330,0,1,1,1,0.0,0,1,0
496,70,478,450,3,92,1,0,1,1,0.0,0,0,0
497,212,369,431,5,476,0,0,1,1,0.0,0,1,0
498,92,129,408,3,49,0,0,1,1,0.0,0,1,0
499,38,354,349,7,168,1,0,1,0,0.0,0,1,0

In [25]:
data.nunique()

study_hours_per_week              500
sleep_hours_per_day               496
attendance_percentage             451
assignments_completed              10
final_grade                       500
participation_level_Low             2
participation_level_Medium          2
internet_access_Yes                 2
parental_education_High School      2
parental_education_Master's         2
parental_education_PhD              2
extracurricular_Yes                 2
part_time_job_Yes                   2
dtype: int64

In [26]:
data["internet_access_Yes"].unique()

array([1, 0])

In [27]:
data.isnull().sum()

study_hours_per_week              0
sleep_hours_per_day               0
attendance_percentage             0
assignments_completed             0
final_grade                       0
participation_level_Low           0
participation_level_Medium        0
internet_access_Yes               0
parental_education_High School    0
parental_education_Master's       0
parental_education_PhD            0
extracurricular_Yes               0
part_time_job_Yes                 0
dtype: int64

In [28]:
x = data.drop('final_grade', axis=1)
y = data['final_grade']

In [29]:
x.head()

,study_hours_per_week,sleep_hours_per_day,attendance_percentage,assignments_completed,participation_level_Low,participation_level_Medium,internet_access_Yes,parental_education_High School,parental_education_Master's,parental_education_PhD,extracurricular_Yes,part_time_job_Yes
0,346,409,449,2,0,1,1,0,0.0,0,1,0
1,219,487,392,5,0,1,1,0,0.0,0,0,0
2,376,36,241,9,0,1,1,0,0.0,0,1,0
3,465,351,115,2,1,0,1,0,0.0,0,1,0
4,201,115,365,3,0,1,1,1,0.0,0,1,0

In [30]:
y.head()

0    431
1    216
2    285
3    320
4    133
Name: final_grade, dtype: int64

In [31]:
data.columns

Index(['study_hours_per_week', 'sleep_hours_per_day', 'attendance_percentage',
       'assignments_completed', 'final_grade', 'participation_level_Low',
       'participation_level_Medium', 'internet_access_Yes',
       'parental_education_High School', 'parental_education_Master's',
       'parental_education_PhD', 'extracurricular_Yes', 'part_time_job_Yes'],
      dtype='str')

In [32]:
from sklearn.preprocessing import LabelEncoder
encoders = {}

def encodeCols(cols):
    for i in cols:
        value = pd.DataFrame({i:data[i].unique()})
        LE = LabelEncoder()
        LE.fit(value)
        data[i] = LE.transform(data[i])
        encoders[i] = LE

columns = ['study_hours_per_week', 'sleep_hours_per_day', 'attendance_percentage',
       'assignments_completed', 'final_grade', 'participation_level_Low',
       'participation_level_Medium', 'internet_access_Yes',
       'parental_education_High School',
       'parental_education_PhD', 'extracurricular_Yes', 'part_time_job_Yes']
encodeCols(columns)

c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [33]:
data['attendance_percentage'] = data['attendance_percentage'].fillna(data['attendance_percentage'].mean())

In [34]:
import joblib
# Save encoders
joblib.dump(encoders, "encoders.pkl")

['encoders.pkl']

In [35]:
output_path = r'C:\Users\zbook\Documents\AI Project\cleaned_data.csv'

try:
	data.to_csv(output_path, index=False)
except PermissionError:
	output_path = r'C:\Users\zbook\Documents\AI Project\cleaned_data_export.csv'
	data.to_csv(output_path, index=False)
	print(f'Original file was locked. Saved data to {output_path} instead.')

In [36]:
data.to_csv('cleaned_data.csv', index=False, header=True)